In [3]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


In [4]:
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(mat)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [6]:
arr2 = np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
arr2 = np.arange(0,25,5)
print(arr2)

[ 0  5 10 15 20]


In [8]:
arr3 = np.linspace(0,5)
print(arr3)

[0.         0.10204082 0.20408163 0.30612245 0.40816327 0.51020408
 0.6122449  0.71428571 0.81632653 0.91836735 1.02040816 1.12244898
 1.2244898  1.32653061 1.42857143 1.53061224 1.63265306 1.73469388
 1.83673469 1.93877551 2.04081633 2.14285714 2.24489796 2.34693878
 2.44897959 2.55102041 2.65306122 2.75510204 2.85714286 2.95918367
 3.06122449 3.16326531 3.26530612 3.36734694 3.46938776 3.57142857
 3.67346939 3.7755102  3.87755102 3.97959184 4.08163265 4.18367347
 4.28571429 4.3877551  4.48979592 4.59183673 4.69387755 4.79591837
 4.89795918 5.        ]


In [13]:
matx4 = np.zeros([3,5])
print(matx4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
arr5 = np.eye(5)
print(arr5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
vec = np.arange(10, 20, 3)
print(vec)

[10 13 16 19]


In [16]:
arr2 = np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
arr2_reshaped = arr2.reshape((2,5))
print(arr2_reshaped)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
print('sine fumction:',np.sin(arr2))
print('cosine function:',np.cos(arr2))
print('tan function:',np.tan(arr2))

sine fumction: [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
cosine function: [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
tan function: [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [19]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
vec = np.arange(0,5) 
print(vec.reshape((2,3)))

ValueError: cannot reshape array of size 5 into shape (2,3)

In [21]:
matrix7 = np.arange(1,10).reshape(3,3)
print(matrix7)
matrix8 = np.eye(3)
print(matrix8)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
print(matrix7+matrix8)

[[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]


In [23]:
print(matrix7*matrix8)

[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [24]:
print(matrix7-matrix8)

[[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]


In [28]:
(matrix7/matrix8)

C:\Users\hp\AppData\Local\Temp\ipykernel_1148\2692608721.py:1: RuntimeWarning: divide by zero encountered in divide
  (matrix7/matrix8)


array([[ 1., inf, inf],
       [inf,  5., inf],
       [inf, inf,  9.]])

In [30]:
matrix9 = np.arange(1,10).reshape(3,3)
print('First Matrix: \n',matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('Second Matrix: \n',matrix10)
print('')
print('multiplication: \n', matrix9 @ matrix10)

First Matrix: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

multiplication: 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [31]:
np.transpose(matrix9)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
# questions
vec1 = np.linspace(20,50,4)
vec2 = np.linspace(100,120,3)
print(vec1 + vec2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [33]:
#question
vec = np.arange(2,5,1)
print(1/vec)
print(vec**2)

[0.5        0.33333333 0.25      ]
[ 4  9 16]


In [34]:
mat1 = np.arange(1,5).reshape(2,2)
mat2 = np.eye(2)
print(mat1/mat2)

[[ 1. inf]
 [inf  4.]]


C:\Users\hp\AppData\Local\Temp\ipykernel_1148\3306162440.py:3: RuntimeWarning: divide by zero encountered in divide
  print(mat1/mat2)


In [36]:
##question
mat1 = np.arange(-9,0,1).reshape(3,3)
print(np.min(mat1))
print(np.max(mat1))

-9
-1


In [37]:
#question
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[1][1])

5


In [38]:
#question
vec = np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [39]:
#question
vec1 = np.array([4, 7, 8, 9, 10, 6, 1])
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


In [48]:
rand_mat3 = np.random.rand(5,5)

In [49]:
print(rand_mat3)

[[0.77178005 0.97692185 0.63815668 0.71198379 0.42475878]
 [0.94910873 0.0759117  0.5255609  0.41966618 0.74953645]
 [0.97777261 0.27779034 0.94188919 0.59681445 0.738663  ]
 [0.31261826 0.52705625 0.00573412 0.98784392 0.22370631]
 [0.27941967 0.34393132 0.97165276 0.72766744 0.977263  ]]


In [50]:
print('matrix before modification: \n',rand_mat3)
rand_mat3[1:3,3:5] = 0
print('matrix after modification: \n',rand_mat3)

matrix before modification: 
 [[0.77178005 0.97692185 0.63815668 0.71198379 0.42475878]
 [0.94910873 0.0759117  0.5255609  0.41966618 0.74953645]
 [0.97777261 0.27779034 0.94188919 0.59681445 0.738663  ]
 [0.31261826 0.52705625 0.00573412 0.98784392 0.22370631]
 [0.27941967 0.34393132 0.97165276 0.72766744 0.977263  ]]
matrix after modification: 
 [[0.77178005 0.97692185 0.63815668 0.71198379 0.42475878]
 [0.94910873 0.0759117  0.5255609  0.         0.        ]
 [0.97777261 0.27779034 0.94188919 0.         0.        ]
 [0.31261826 0.52705625 0.00573412 0.98784392 0.22370631]
 [0.27941967 0.34393132 0.97165276 0.72766744 0.977263  ]]


In [52]:
sub_mat = rand_mat3[0:2,0:3]
print(sub_mat)

[[0.77178005 0.97692185 0.63815668]
 [0.94910873 0.0759117  0.5255609 ]]


In [53]:
sub_mat[:] = 3
print(sub_mat)

[[3. 3. 3.]
 [3. 3. 3.]]


In [54]:
rand_mat3

array([[3.        , 3.        , 3.        , 0.71198379, 0.42475878],
       [3.        , 3.        , 3.        , 0.        , 0.        ],
       [0.97777261, 0.27779034, 0.94188919, 0.        , 0.        ],
       [0.31261826, 0.52705625, 0.00573412, 0.98784392, 0.22370631],
       [0.27941967, 0.34393132, 0.97165276, 0.72766744, 0.977263  ]])

In [55]:
rand_mat = np.random.randn(5,5)
print(rand_mat)
sub_mat = rand_mat[0:2,0:3].copy()
sub_mat[:] = 3
print(sub_mat)
print(rand_mat)

[[-0.11555409 -0.30802722  0.10827828  1.85248801  1.11773806]
 [-1.05365555 -1.11038125  0.82941843  0.20858988 -1.03596245]
 [-0.95784416 -1.08310724 -0.79915293  0.55650475 -0.78049821]
 [-0.65041138 -1.77235631 -0.17736175 -0.37619216  0.16453222]
 [ 0.96745166 -0.14336118 -1.38600867  0.73825185 -0.63362734]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[-0.11555409 -0.30802722  0.10827828  1.85248801  1.11773806]
 [-1.05365555 -1.11038125  0.82941843  0.20858988 -1.03596245]
 [-0.95784416 -1.08310724 -0.79915293  0.55650475 -0.78049821]
 [-0.65041138 -1.77235631 -0.17736175 -0.37619216  0.16453222]
 [ 0.96745166 -0.14336118 -1.38600867  0.73825185 -0.63362734]]


In [56]:
#question
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [57]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1